image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install dependencies
    init: composer install

vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - hbenl.test-adapter-converter
    - recca0120.vscode-phpunit
