name: Deploy

on:
  push:
    branches: [main]
    tags: ["v*"]

jobs:
  build-and-push-docker-image:
    name: "Build and push to DockerHub"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Login to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Extract metadata for Docker"
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: davidrjenni/lsif-php

      - name: "Build and push"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
